// <auto-generated />
using System;
using EvidenceChain.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EvidenceChain.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261009044612_InboxIntegrityCheckedIndex")]
    partial class InboxIntegrityCheckedIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EvidenceChain.Domain.Catalog.DailyCounter", b =>
                {
                    b.Property<string>("TypeCode")
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<short>("LastNo")
                        .HasColumnType("smallint");

                    b.HasKey("TypeCode", "Day");

                    b.ToTable("DailyCounter", null, t =>
                        {
                            t.HasCheckConstraint("CK_DailyCounter_LastNo", "[LastNo] BETWEEN 1 AND 9999");
                        });
                });

            modelBuilder.Entity("EvidenceChain.Domain.Catalog.Evidence", b =>
                {
                    b.Property<long>("EvidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EvidenceId"));

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasComputedColumnSql("CONCAT([TypeCode], CONVERT(char(8), [CodeDateUtc], 112), RIGHT(CONCAT('000', [DailyNo]), 4)) COLLATE Latin1_General_100_BIN2", true);

                    b.Property<DateOnly>("CodeDateUtc")
                        .HasColumnType("date");

                    b.Property<int>("CurrentCustodianId")
                        .HasColumnType("int");

                    b.Property<short>("DailyNo")
                        .HasColumnType("smallint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EventCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<byte[]>("HeadMac")
                        .HasColumnType("binary(32)");

                    b.Property<int>("InitialCustodianId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDemoFixture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RegisteredById")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("EvidenceId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Evidence_Code");

                    b.HasIndex("CurrentCustodianId");

                    b.HasIndex("InitialCustodianId");

                    b.HasIndex("RegisteredById");

                    b.HasIndex("CodeDateUtc", "EvidenceId")
                        .IsDescending()
                        .HasDatabaseName("IX_Evidence_Recent");

                    b.HasIndex("TypeCode", "CodeDateUtc", "DailyNo")
                        .IsUnique()
                        .HasDatabaseName("UX_Evidence_TypeDateNo");

                    b.ToTable("Evidence", null, t =>
                        {
                            t.HasTrigger("TR_Evidence_InitialCustodianImmutable");

                            t.HasCheckConstraint("CK_Evidence_CapturedBeforeRegistered", "[CapturedAtUtc] <= [RegisteredAtUtc]");

                            t.HasCheckConstraint("CK_Evidence_CodeDateIsRegistrationDate", "[CodeDateUtc] = CONVERT(date, [RegisteredAtUtc])");

                            t.HasCheckConstraint("CK_Evidence_DailyNo", "[DailyNo] BETWEEN 1 AND 9999");

                            t.HasCheckConstraint("CK_Evidence_Head", "([EventCount] = 0 AND [HeadMac] IS NULL) OR ([EventCount] > 0 AND [HeadMac] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Evidence_TypeCode", "[TypeCode] IN ('LOG', 'CSV', 'EML')");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("EvidenceChain.Domain.Catalog.EvidenceContent", b =>
                {
                    b.Property<long>("EvidenceId")
                        .HasColumnType("bigint");

                    b.Property<int>("ByteLength")
                        .HasColumnType("int");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.HasKey("EvidenceId");

                    b.ToTable("EvidenceContent", null, t =>
                        {
                            t.HasCheckConstraint("CK_EvidenceContent_Length", "[ByteLength] = DATALENGTH([Bytes])");
                        });
                });

            modelBuilder.Entity("EvidenceChain.Domain.Custody.CustodyEvent", b =>
                {
                    b.Property<long>("CustodyEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CustodyEventId"));

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<byte>("CanonicalVersion")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ContentLength")
                        .HasColumnType("int");

                    b.Property<byte[]>("ContentSha256")
                        .HasColumnType("binary(32)");

                    b.Property<long>("EvidenceId")
                        .HasColumnType("bigint");

                    b.Property<int?>("FromCustodianId")
                        .HasColumnType("int");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<byte[]>("Mac")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<string>("MediaType")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PrevMac")
                        .HasColumnType("binary(32)");

                    b.Property<int>("Seq")
                        .HasColumnType("int");

                    b.Property<int?>("ToCustodianId")
                        .HasColumnType("int");

                    b.Property<long?>("TransferId")
                        .HasColumnType("bigint");

                    b.HasKey("CustodyEventId");

                    b.HasIndex("ActorId");

                    b.HasIndex("FromCustodianId");

                    b.HasIndex("ToCustodianId");

                    b.HasIndex("EvidenceId", "Seq")
                        .IsUnique()
                        .HasDatabaseName("UX_CustodyEvents_EvidenceSeq");

                    b.HasIndex("TransferId", "EvidenceId");

                    b.ToTable("CustodyEvents", null, t =>
                        {
                            t.HasTrigger("TR_CustodyEvents_AppendOnly");

                            t.HasCheckConstraint("CK_CustodyEvents_Kind", "[Kind] IN ('EvidenceRegistered', 'TransferRequested', 'TransferAccepted', 'TransferRejected')");

                            t.HasCheckConstraint("CK_CustodyEvents_Shape", "([Seq] = 1 AND [Kind] = 'EvidenceRegistered' AND [PrevMac] IS NULL AND [TransferId] IS NULL AND [FromCustodianId] IS NULL AND [ToCustodianId] IS NOT NULL AND [ContentSha256] IS NOT NULL AND [ContentLength] >= 0 AND [MediaType] IS NOT NULL) OR ([Seq] > 1 AND [Kind] <> 'EvidenceRegistered' AND [PrevMac] IS NOT NULL AND [TransferId] IS NOT NULL AND [FromCustodianId] IS NOT NULL AND [ToCustodianId] IS NOT NULL AND [ContentSha256] IS NULL AND [ContentLength] IS NULL AND [MediaType] IS NULL)");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("EvidenceChain.Domain.Custody.CustodyTransfer", b =>
                {
                    b.Property<long>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TransferId"));

                    b.Property<Guid>("ClientRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DecidedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DecidedById")
                        .HasColumnType("int");

                    b.Property<byte[]>("DecisionFingerprint")
                        .HasColumnType("binary(32)");

                    b.Property<Guid?>("DecisionKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DecisionNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("EvidenceId")
                        .HasColumnType("bigint");

                    b.Property<int>("FromCustodianId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RequestFingerprint")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestedById")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<int>("ToCustodianId")
                        .HasColumnType("int");

                    b.HasKey("TransferId");

                    b.HasIndex("EvidenceId")
                        .IsUnique()
                        .HasDatabaseName("UX_CustodyTransfers_OnePendingPerEvidence")
                        .HasFilter("[Status] = 'Pending'");

                    b.HasIndex("FromCustodianId");

                    b.HasIndex("DecidedById", "DecisionKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CustodyTransfers_DecisionKey")
                        .HasFilter("[DecisionKey] IS NOT NULL");

                    b.HasIndex("EvidenceId", "TransferId")
                        .HasDatabaseName("IX_CustodyTransfers_Evidence");

                    b.HasIndex("RequestedById", "ClientRequestId")
                        .IsUnique()
                        .HasDatabaseName("UX_CustodyTransfers_RequestKey");

                    b.HasIndex("ToCustodianId", "Status")
                        .HasDatabaseName("IX_CustodyTransfers_RecipientStatus");

                    b.ToTable("CustodyTransfers", null, t =>
                        {
                            t.HasCheckConstraint("CK_CustodyTransfers_Decision", "([Status] = 'Pending' AND [DecidedAtUtc] IS NULL AND [DecidedById] IS NULL AND [DecisionKey] IS NULL AND [DecisionFingerprint] IS NULL) OR ([Status] <> 'Pending' AND [DecidedAtUtc] IS NOT NULL AND [DecidedAtUtc] >= [RequestedAtUtc] AND [DecidedById] IS NOT NULL AND [DecisionKey] IS NOT NULL AND [DecisionFingerprint] IS NOT NULL)");

                            t.HasCheckConstraint("CK_CustodyTransfers_DifferentRecipient", "[FromCustodianId] <> [ToCustodianId]");

                            t.HasCheckConstraint("CK_CustodyTransfers_RecipientDecides", "[DecidedById] IS NULL OR [DecidedById] = [ToCustodianId]");

                            t.HasCheckConstraint("CK_CustodyTransfers_Status", "[Status] IN ('Pending', 'Accepted', 'Rejected')");
                        });
                });

            modelBuilder.Entity("EvidenceChain.Domain.People.User", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .IsUnicode(false)
                        .HasColumnType("varchar(254)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Email");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_UserName");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "[Role] IN ('Investigador', 'Custodio', 'Supervisor')");
                        });
                });

            modelBuilder.Entity("EvidenceChain.Infrastructure.Persistence.ReadModels.EvidenceInboxRow", b =>
                {
                    b.Property<long>("EvidenceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateOnly>("CodeDateUtc")
                        .HasColumnType("date");

                    b.Property<int>("CurrentCustodianId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentCustodianName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EventCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IntegrityCheckedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IntegrityCheckedThroughSeq")
                        .HasColumnType("int");

                    b.Property<string>("IntegrityStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("LastEventAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PendingSinceUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PendingToCustodianId")
                        .HasColumnType("int");

                    b.Property<long?>("PendingTransferId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("EvidenceId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_EvidenceInbox_Code");

                    b.HasIndex("IntegrityCheckedAtUtc", "EvidenceId")
                        .HasDatabaseName("IX_EvidenceInbox_IntegrityChecked");

                    b.HasIndex("LastEventAtUtc", "EvidenceId")
                        .IsDescending()
                        .HasDatabaseName("IX_EvidenceInbox_Recent");

                    b.HasIndex("CurrentCustodianId", "LastEventAtUtc", "EvidenceId")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("IX_EvidenceInbox_Custodian");

                    b.HasIndex("IntegrityStatus", "LastEventAtUtc", "EvidenceId")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("IX_EvidenceInbox_Integrity");

                    b.HasIndex("TypeCode", "LastEventAtUtc", "EvidenceId")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("IX_EvidenceInbox_Type");

                    b.ToTable("EvidenceInbox", null, t =>
                        {
                            t.HasCheckConstraint("CK_EvidenceInbox_IntegrityStatus", "[IntegrityStatus] IN ('Unverified', 'Valid', 'Invalid')");
                        });
                });

            modelBuilder.Entity("EvidenceChain.Infrastructure.Persistence.SeedRun", b =>
                {
                    b.Property<int>("SeedRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeedRunId"));

                    b.Property<DateTime>("AnchorUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Arguments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Events")
                        .HasColumnType("int");

                    b.Property<int>("Evidences")
                        .HasColumnType("int");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<long>("Seed")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("SeedRunId");

                    b.ToTable("SeedRuns", (string)null);
                });

            modelBuilder.Entity("EvidenceChain.Domain.Catalog.Evidence", b =>
                {
                    b.HasOne("EvidenceChain.Domain.People.User", null)
                        .WithMany()
                        .HasForeignKey("CurrentCustodianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EvidenceChain.Domain.People.User", null)
                        .WithMany()
                        .HasForeignKey("InitialCustodianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EvidenceChain.Domain.People.User", null)
                        .WithMany()
                        .HasForeignKey("RegisteredById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EvidenceChain.Domain.Catalog.EvidenceContent", b =>
                {
                    b.HasOne("EvidenceChain.Domain.Catalog.Evidence", null)
                        .WithOne("Content")
                        .HasForeignKey("EvidenceChain.Domain.Catalog.EvidenceContent", "EvidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EvidenceChain.Domain.Custody.CustodyEvent", b =>
                {
                    b.HasOne("EvidenceChain.Domain.People.User", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EvidenceChain.Domain.Catalog.Evidence", null)
                        .WithMany()
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EvidenceChain.Domain.People.User", null)
                        .WithMany()
                        .HasForeignKey("FromCustodianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EvidenceChain.Domain.People.User", null)
                        .WithMany()
                        .HasForeignKey("ToCustodianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EvidenceChain.Domain.Custody.CustodyTransfer", null)
                        .WithMany()
                        .HasForeignKey("TransferId", "EvidenceId")
                        .HasPrincipalKey("TransferId", "EvidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_CustodyEvents_CustodyTransfers_TransferEvidence");
                });

            modelBuilder.Entity("EvidenceChain.Domain.Custody.CustodyTransfer", b =>
                {
                    b.HasOne("EvidenceChain.Domain.People.User", null)
                        .WithMany()
                        .HasForeignKey("DecidedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EvidenceChain.Domain.Catalog.Evidence", null)
                        .WithMany()
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EvidenceChain.Domain.People.User", null)
                        .WithMany()
                        .HasForeignKey("FromCustodianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EvidenceChain.Domain.People.User", null)
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EvidenceChain.Domain.People.User", null)
                        .WithMany()
                        .HasForeignKey("ToCustodianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EvidenceChain.Infrastructure.Persistence.ReadModels.EvidenceInboxRow", b =>
                {
                    b.HasOne("EvidenceChain.Domain.Catalog.Evidence", null)
                        .WithOne()
                        .HasForeignKey("EvidenceChain.Infrastructure.Persistence.ReadModels.EvidenceInboxRow", "EvidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EvidenceChain.Domain.Catalog.Evidence", b =>
                {
                    b.Navigation("Content")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
