// <auto-generated />
using System;
using EvidenceChain.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EvidenceChain.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008232435_InitialTracer")]
    partial class InitialTracer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EvidenceChain.Domain.Catalog.Evidence", b =>
                {
                    b.Property<long>("EvidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EvidenceId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasComputedColumnSql("CONCAT([TypeCode], CONVERT(char(8), [CodeDateUtc], 112), RIGHT(CONCAT('000', [DailyNo]), 4)) COLLATE Latin1_General_100_BIN2", true);

                    b.Property<DateOnly>("CodeDateUtc")
                        .HasColumnType("date");

                    b.Property<short>("DailyNo")
                        .HasColumnType("smallint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("EvidenceId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Evidence_Code");

                    b.HasIndex("CodeDateUtc", "EvidenceId")
                        .IsDescending()
                        .HasDatabaseName("IX_Evidence_Recent");

                    b.HasIndex("TypeCode", "CodeDateUtc", "DailyNo")
                        .IsUnique()
                        .HasDatabaseName("UX_Evidence_TypeDateNo");

                    b.ToTable("Evidence", null, t =>
                        {
                            t.HasCheckConstraint("CK_Evidence_DailyNo", "[DailyNo] BETWEEN 1 AND 9999");

                            t.HasCheckConstraint("CK_Evidence_TypeCode", "[TypeCode] IN ('LOG', 'CSV', 'EML')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
